import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import path from "path";
import { componentTagger } from "lovable-tagger";
import { VitePWA } from 'vite-plugin-pwa';

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  server: {
      host: "::",
          port: 8080,
            },
              plugins: [
                  react(), 
                      mode === "development" && componentTagger(),
                          VitePWA({
                                registerType: 'autoUpdate',
                                      includeAssets: ['favicon.ico', 'robots.txt'],
                                            manifest: {
                                                    name: 'Eats\'Kale - Track • Tweak • Triumph',
                                                            short_name: 'Eats\'Kale',
                                                                    description: 'AI-powered food tracking with instant meal recognition',
                                                                            theme_color: '#10b981',
                                                                                    background_color: '#ffffff',
                                                                                            display: 'standalone',
                                                                                                    orientation: 'portrait',
                                                                                                            scope: '/',
                                                                                                                    start_url: '/',
                                                                                                                            icons: [
                                                                                                                                      {
                                                                                                                                                  src: '/placeholder.svg',
                                                                                                                                                              sizes: '192x192',
                                                                                                                                                                          type: 'image/svg+xml',
                                                                                                                                                                                      purpose: 'any maskable'
                                                                                                                                                                                                },
                                                                                                                                                                                                          {
                                                                                                                                                                                                                      src: '/placeholder.svg',
                                                                                                                                                                                                                                  sizes: '512x512',
                                                                                                                                                                                                                                              type: 'image/svg+xml',
                                                                                                                                                                                                                                                          purpose: 'any maskable'
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                        workbox: {
                                                                                                                                                                                                                                                                                                globPatterns: ['**/*.{js,css,html,ico,png,svg,woff2}'],
                                                                                                                                                                                                                                                                                                        runtimeCaching: [
                                                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                                                              urlPattern: /^https:\/\/.*\.supabase\.co\/.*/i,
                                                                                                                                                                                                                                                                                                                                          handler: 'NetworkFirst',
                                                                                                                                                                                                                                                                                                                                                      options: {
                                                                                                                                                                                                                                                                                                                                                                    cacheName: 'supabase-cache',
                                                                                                                                                                                                                                                                                                                                                                                  expiration: {
                                                                                                                                                                                                                                                                                                                                                                                                  maxEntries: 50,
                                                                                                                                                                                                                                                                                                                                                                                                                  maxAgeSeconds: 60 * 60 * 24 // 24 hours
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                              ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ].filter(Boolean),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            resolve: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                alias: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "@": path.resolve(__dirname, "./src"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            